id: P007006
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14532
  title: ཕའེ་གུན་ནས་མི་ཚེ་གླེང་བ།
  author: ''
  volumes:
    308e2d4843c740d9add50239595e2ab3:
      image_group_id: I1KG15680
      title: ''
      volume_number: 1
      total_pages: 156
ebook_metadata:
  title: ཕའེ་གུན་ནས་མི་ཚེ་གླེང་བ།
  author: ''
  sku: P007006
  cover: cover.jpg
  layers:
  - pagination
