id: P007006
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG14532
  title: ཕའེ་གུན་ནས་མི་ཚེ་གླེང་བ།
  author: ''
  volumes:
    b4ea634e19ce48c99718626fe54ff116:
      image_group_id: I1KG15680
      title: Volume 1 of pha'e gun nas mi tshe gleng ba/
      volume_number: 1
      total_pages: 156
      base_file: v001.txt
