id: I83133518
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T18:58:27+00:00'
last_modified: '2022-06-08T11:54:17.525690+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14532
  title: ཕའེ་གུན་ནས་མི་ཚེ་གླེང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    63A9:
      image_group_id: I1KG15680
      title: Volume 1 of pha'e gun nas mi tshe gleng ba/
      total_pages: 156
      order: 1
      base_file: 63A9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
